# -*- coding: utf-8 -*-
"""Langchain with groq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPxcdQh-qgdpkkHlOyOYgpRw5fGoYBeO
"""

!pip install langchain langchain-groq langchain-community langchain-core --quiet

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Set API Key
os.environ["GROQ_API_KEY"] = "gsk_wRPnvxbog(ENTER API KEY)Y9uUHypaMgtwwcM"

# Load LLM
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.4
)

# Create Prompt Template
prompt = PromptTemplate(
    input_variables=["topic"],
    template="Build the basic conversation between {topic} in simple terms"
)

# Output Parser
parser = StrOutputParser()

# Create Chain
chain = prompt | llm | parser

# Run Chain
response = chain.invoke({"topic": "teacher and student"})   #its start the entire program

# Print Response
print(response)

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser


# Initialize LLM
llm = ChatGroq(model="Llama-3.3-70b-versatile", temperature=0.5)
parser = StrOutputParser()


# Helper function to run chains with neat formatting
def run_task(task_name, prompt, inputs):
    chain = prompt | llm | parser
    output = chain.invoke(inputs)
    print("\n" + "="*50 )
    print(f" Task: {task_name}")
    print("="*50)
    print(f" Input: {inputs}")
    print(f" Output: {output}")
    print("="*50 + "\n")


# ------------------------
# 1. Title Generation
prompt = PromptTemplate(
    input_variables=["text"],
    template="Generate a short and catchy title for the following text:\n\n{text}\n\nTitle:"
)
run_task("Title Generation", prompt, {"text": "AI is transforming industries across the world"})


# ------------------------
# 2. Grammar Correction
prompt = PromptTemplate(
    input_variables=["sentence"],
    template="Correct the grammar of this sentence:\n\n{sentence}\n\nCorrected:"
)
run_task("Grammar Correction", prompt, {"sentence": "He go to school everyday"})


# ------------------------
# 3. Bullet Point Notes
prompt = PromptTemplate(
    input_variables=["paragraph"],
    template="Convert the following paragraph into 3 concise bullet points:\n\n{paragraph}\n\nBullet Points:"
)
run_task("Bullet Point Notes", prompt, {
    "paragraph": "Python is widely used in AI development. It has a huge ecosystem of libraries. Many developers prefer it for its simplicity."
})


# ------------------------
# 4. Comparison Task
prompt = PromptTemplate(
    input_variables=["item1", "item2"],
    template="Compare {item1} and {item2} in 3 bullet points."
)
run_task("Comparison Task", prompt, {"item1": "Python", "item2": "Java"})


# ------------------------
# 5. Emoji Translation
prompt = PromptTemplate(
    input_variables=["sentence"],
    template="Translate this sentence into emojis:\n\n{sentence}\n\nEmojis:"
)
run_task("Emoji Translation", prompt, {"sentence": "I love eating pizza on weekends"})


# ------------------------
# 6. Hashtag Generator
prompt = PromptTemplate(
    input_variables=["topic"],
    template="Generate 5 trending hashtags for {topic}."
)
run_task("Hashtag Generator", prompt, {"topic": "Artificial Intelligence"})


# ------------------------
# 7. SQL Query Generator
prompt = PromptTemplate(
    input_variables=["request"],
    template="Write a SQL query for the following request:\n\n{request}\n\nSQL:"
)
run_task("SQL Query Generator", prompt, {"request": "Find all employees who joined after 2020"})


# ------------------------
# 8. Interview Question Creator
prompt = PromptTemplate(
    input_variables=["role"],
    template="Generate 3 common interview questions for the role of {role}."
)
run_task("Interview Question Creator", prompt, {"role": "Data Scientist"})


# ------------------------
# 9. Bug Finder (Code Debugging)
prompt = PromptTemplate(
    input_variables=["code"],
    template="Find the bug in the following Python code and suggest a fix:\n\n{code}\n\nBug and Fix:"
)
run_task("Bug Finder (Debugging)", prompt, {"code": "for i in range(5)\n    print(i)"})


# ------------------------
# 10. Story Starter
prompt = PromptTemplate(
    input_variables=["theme"],
    template="Write the opening 2 sentences of a short story about {theme}."
)
run_task("Story Starter", prompt, {"theme": "a robot discovering emotions"})