# -*- coding: utf-8 -*-
"""Transformer using hugginface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ocXS-voXIacAevd8a_svwtqq4RmuV5o

Sentiment Analysis using Transformers

In this project, I learned how to perform Sentiment Analysis using the Transformers library in Python. The model checks whether the given text is positive or negative.

I used a pre-trained DistilBERT model from Hugging Face, so there was no need to train the model manually.

--------------------------------------------------

Libraries Used

pip install transformers datasets sentence-transformers diffusers accelerate huggingface_hub[cli] torchvision pillow scikit-learn

Packages Used and Their Usage

1. transformers

Usage:
The transformers library is used to load and use pre-trained AI models for NLP tasks.

Main Uses:
- Sentiment Analysis
- Chatbots
- Translation
- Text Summarization
- Question Answering

In this project:
Used to load the DistilBERT sentiment analysis model.

Example:
from transformers import pipeline

--------------------------------------------------

2. datasets

Usage:
The datasets library is used to load and manage machine learning datasets easily.

Main Uses:
- Load NLP datasets
- Training AI models
- Data preprocessing
- Benchmark testing

Example:
Used when training or testing NLP models with large datasets.

--------------------------------------------------

3. sentence-transformers

Usage:
Used to generate sentence embeddings (vector representations of text).

Main Uses:
- Semantic search
- Similarity checking
- Recommendation systems
- AI search engines

Example:
Convert a sentence into vectors for similarity comparison.

--------------------------------------------------

4. diffusers

Usage:
Used for AI image generation models.

Main Uses:
- Text-to-image generation
- Stable Diffusion models
- Image editing
- AI art generation

Example:
Generate images from text prompts.

--------------------------------------------------

5. accelerate

Usage:
Helps run AI models faster and more efficiently.

Main Uses:
- GPU optimization
- Faster training
- Multi-device support
- Memory optimization

Example:
Used while training large AI models.

--------------------------------------------------

6. huggingface_hub[cli]

Usage:
Connects Python projects with Hugging Face Hub.

Main Uses:
- Download models
- Upload models
- Access AI repositories
- CLI login support

Example:
Download pre-trained models directly from Hugging Face.

--------------------------------------------------

7. torchvision

Usage:
PyTorch library for computer vision tasks.

Main Uses:
- Image preprocessing
- Image datasets
- Deep learning vision models
- Image transformations

Example:
Used in image classification projects.

--------------------------------------------------

8. pillow

Usage:
Python image processing library.

Main Uses:
- Open images
- Resize images
- Edit images
- Convert image formats

Example:
Used before sending images into AI models.

--------------------------------------------------

9. scikit-learn

Usage:
Machine Learning library for traditional ML algorithms.

Main Uses:
- Classification
- Regression
- Clustering
- Data preprocessing
- Model evaluation

Example:
Used for Decision Trees, Random Forest, Logistic Regression, etc.

--------------------------------------------------

What I Learned

1. Transformers Library

The Transformers library provides ready-made AI models for NLP tasks like:
- Sentiment Analysis
- Translation
- Text Summarization
- Chatbots

It helps developers use powerful AI models with very little code.

--------------------------------------------------

2. Pipeline

The pipeline() function makes the process simple.

Example:

pipeline("sentiment-analysis")

It automatically:
- Loads the model
- Converts text into tokens
- Runs prediction
- Returns the result

Without pipeline, we need to write many lines of code manually.

--------------------------------------------------

3. Sentiment Analysis

Sentiment Analysis means identifying the emotion or opinion in a sentence.

Example:

Input:
"I love this product"

Output:
Positive

Another Example:

Input:
"This movie is bad"

Output:
Negative

Uses:
- Customer feedback analysis
- Product review checking
- Social media monitoring
- Business feedback systems

--------------------------------------------------

4. DistilBERT Model

Model Used:
distilbert-base-uncased-finetuned-sst-2-english

This is a smaller and faster version of the BERT model.

Features:
- Fast execution
- Less memory usage
- Good accuracy
- Easy to use

--------------------------------------------------

5. Tokenization

AI models cannot understand raw text directly.

So the sentence is split into smaller parts called tokens.

Example:

"I love AI"

becomes

["I", "love", "AI"]

These tokens are later converted into numbers for the AI model.

--------------------------------------------------

Workflow

User Input
   ↓
Tokenizer
   ↓
DistilBERT Model
   ↓
Sentiment Prediction
   ↓
Final Output

--------------------------------------------------

Example Output

[{'label': 'POSITIVE', 'score': 0.9998}]

Meaning:
- POSITIVE → Predicted sentiment
- score → Confidence level

--------------------------------------------------

Conclusion

This project helped me understand how NLP models work for text classification tasks. I learned about Transformers, tokenization, pipelines, and how pre-trained AI models can be used easily in Python for sentiment analysis.
"""

# Install Required Libraries
!pip install transformers datasets sentence-transformers diffusers accelerate huggingface_hub[cli] torchvision pillow scikit-learn -quiet

#sentiment analysis
from transformers import pipeline
classifier = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")
text=input("Enter a text")
result=classifier(text)
print(result)